name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  check-publication:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
      - name: Check publication
        run: bash .github/workflows/scripts/check_publication.sh
